import type { Metadata } from "next"
import { SimpleHeader } from "../app/components/SimpleHeader"
import { Footer } from "../app/components/Footer"
import React, { Suspense } from "react"
import "./styles/globals.css"
import Loading from "./loading"
import MiniCartModule from "./components/MiniCartModule"

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body>
                <SimpleHeader />
                {/* <MiniCartModule /> */}
                <Suspense fallback={<Loading />}>{children}</Suspense>
                <Footer />
            </body>
        </html>
    )
}
